IP = "192.168.11.110"
vm_box = 'ubu14'

Vagrant.configure('2') do |config|
  config.vm.define :empty do |box|
    box.vm.box = vm_box
    box.vm.synced_folder ".", "/vagrant", disabled: false 
    box.vm.network :private_network, ip: "#{IP}"
    box.vm.hostname = 'GG'
    box.vm.provision "shell", inline: "apt-get install git; git clone https://github.com/aol/moloch.git; cd moloch; echo -en '\n\n\n\n'| ./easybutton-singlehost.sh "
    box.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
  end
end
