IP = "192.168.11.113"
vm_box = 'ubu14'

Vagrant.configure('2') do |config|
  config.vm.define :single do |box|
    box.vm.box = vm_box
    #box.vm.synced_folder ".", "/vagrant", disabled: false
    box.vm.network :private_network, ip: "#{IP}"
    box.vm.hostname = 'single'
    box.vm.provision :shell, :path => "./my-custom-install.sh", args: "first_arg second_arg"
    box.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
  end
end
