IP = "192.168.11.111"
vm_box = 'ubu14'

Vagrant.configure('2') do |config|
  config.vm.define :Dummy do |box|
    box.vm.box = vm_box
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.network :private_network, ip: "#{IP}"
    box.vm.hostname = 'Dummy'
    box.vm.provision :shell, :path => "./scripts/dummy-install-suricata.sh", args: "eth1"
    box.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
  end
end
