IP = "192.168.11.110"
vm_box = 'ubu14'

Vagrant.configure('2') do |config|
  config.vm.define :empty do |box|
    box.vm.box = vm_box
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.network :private_network, ip: "#{IP}"
    box.vm.hostname = 'Empty'
    box.vm.provision "shell", inline: "ifconfig; ping -c 1 www.ee; netstat -ntple"
    box.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
  end
end
